-- 코드를 입력하세요
WITH GROUP_BY_CATEGORY AS (
    SELECT AUTHOR_ID, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
    FROM BOOK B JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
    GROUP BY CATEGORY, AUTHOR_ID
)

SELECT G.AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES
FROM GROUP_BY_CATEGORY G JOIN AUTHOR A
ON G.AUTHOR_ID = A.AUTHOR_ID
ORDER BY 1, 3 DESC;