-- 코드를 입력하세요
WITH EXIST_MILK_TABLE AS (
    SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)

SELECT DISTINCT m.CART_ID
FROM EXIST_MILK_TABLE m
JOIN (SELECT CART_ID FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt') y
ON m.CART_ID = y.CART_ID
ORDER BY 1;