SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', CONCAT(f.FILE_ID, f.FILE_NAME, f.FILE_EXT))
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_FILE f ON b.BOARD_ID = f.BOARD_ID
WHERE (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) = b.VIEWS
ORDER BY FILE_ID DESC;
