-- 코드를 작성해주세요
WITH SIZE_RANK AS(
SELECT ID, rank() over (order by SIZE_OF_COLONY DESC) as 'R' FROM ECOLI_DATA)

SELECT ID,
CASE
WHEN R / (SELECT COUNT(ID) FROM ECOLI_DATA) <= 0.25 THEN 'CRITICAL'
WHEN R / (SELECT COUNT(ID) FROM ECOLI_DATA) <= 0.50 THEN 'HIGH'
WHEN R / (SELECT COUNT(ID) FROM ECOLI_DATA) <= 0.75 THEN 'MEDIUM'
WHEN R / (SELECT COUNT(ID) FROM ECOLI_DATA) <= 1 THEN 'LOW'
END AS 'COLONY_NAME'
FROM SIZE_RANK
ORDER BY ID;