-- 코드를 입력하세요
WITH JOIN_2021_USERS AS (
    SELECT * FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT o.USER_ID) AS PURCHASED_USERS, 
ROUND(count(DISTINCT o.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE o
JOIN JOIN_2021_USERS j
ON o.USER_ID = j.USER_ID
GROUP BY 1, 2
ORDER BY 1, 2