-- 코드를 작성해주세요

WITH QUARTER_TABLE AS (
    SELECT
    CASE
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3 THEN 1
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6 THEN 2
    WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9 THEN 3
    ELSE 4
    END AS QUARTER
    FROM ECOLI_DATA
)

SELECT
CONCAT(QUARTER, 'Q') AS 'QUARTER',
COUNT(*) AS ECOLI_COUNT
FROM QUARTER_TABLE
GROUP BY QUARTER
ORDER BY QUARTER