-- 코드를 입력하세요
WITH HEAVY_USER_TABLE AS (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) >= 2
)

SELECT ID, NAME, p.HOST_ID
FROM PLACES p
JOIN HEAVY_USER_TABLE h
ON p.HOST_ID = h.HOST_ID
ORDER BY 1;