-- 코드를 입력하세요
WITH TOTAL_TABLE AS (
    SELECT f.SHIPMENT_ID, SUM(f.TOTAL_ORDER + j.TOTAL_ORDER) AS TOTAL
    FROM FIRST_HALF f
    JOIN JULY j
    ON f.FLAVOR = j.FLAVOR
    GROUP BY f.FLAVOR
    ORDER BY 2 DESC
    LIMIT 3
)

SELECT FLAVOR
FROM FIRST_HALF f
JOIN TOTAL_TABLE t
ON f.SHIPMENT_ID = t.SHIPMENT_ID
ORDER BY t.TOTAL DESC;
