-- 코드를 입력하세요
WITH PATIENT_APNT AS (
    SELECT p.PT_NO, PT_NAME, MDDR_ID, APNT_YMD, APNT_NO
    FROM PATIENT p
    JOIN APPOINTMENT a
    ON p.PT_NO = a.PT_NO
    WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' 
    AND MCDP_CD='CS'
    AND APNT_CNCL_YMD IS NULL
)

SELECT APNT_NO, PT_NAME, PT_NO, MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT_APNT pa
JOIN DOCTOR d
ON pa.MDDR_ID = d.DR_ID
ORDER BY 6;