-- 코드를 입력하세요
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT HOUR, COUNT(DATETIME) AS 'COUNT'
FROM TIME_TABLE LEFT JOIN ANIMAL_OUTS
ON HOUR = HOUR(DATETIME)
GROUP BY 1
ORDER BY 1;