-- 코드를 작성해주세요
WITH GRADE_AVG_TABLE AS (
    SELECT e.EMP_NO, FLOOR(AVG(SCORE)) AS AVERAGE
    FROM HR_EMPLOYEES e JOIN HR_GRADE g
    ON e.EMP_NO = g.EMP_NO
    GROUP BY e.EMP_NO
)

SELECT e.EMP_NO, EMP_NAME,
CASE
WHEN AVERAGE >= 96 THEN 'S'
WHEN AVERAGE >= 90 THEN 'A'
WHEN AVERAGE >= 80 THEN 'B'
ELSE 'C'
END AS GRADE,
CASE
WHEN AVERAGE >= 96 THEN SAL * 0.2
WHEN AVERAGE >= 90 THEN SAL * 0.15
WHEN AVERAGE >= 80 THEN SAL * 0.1
ELSE 0
END AS BONUS
FROM HR_EMPLOYEES e JOIN GRADE_AVG_TABLE g
ON e.EMP_NO = g.EMP_NO
ORDER BY 1;