-- 코드를 입력하세요
WITH MAX_REVIEW_WRITER AS (
    SELECT m.MEMBER_ID, MEMBER_NAME
    FROM MEMBER_PROFILE m
    JOIN REST_REVIEW r
    ON m.MEMBER_ID = r.MEMBER_ID
    GROUP BY m.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r
JOIN MAX_REVIEW_WRITER m
ON r.MEMBER_ID = m.MEMBER_ID
ORDER BY 3, 2