-- 코드를 작성해주세요
WITH MAX_SIZE_BY_YEAR AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS `YEAR`, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY 1
)

SELECT M.`YEAR`, M.MAX_SIZE - SIZE_OF_COLONY AS 'YEAR_DEV', ID
FROM ECOLI_DATA E
JOIN MAX_SIZE_BY_YEAR M
ON M.`YEAR` = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY 1, 2;