-- 코드를 작성해주세요
WITH MAX_SIZE_OF_COLONY AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
    MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY 1
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR,
E2.MAX - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA E1
JOIN MAX_SIZE_OF_COLONY E2
ON YEAR(DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY 1, 2;