-- 코드를 작성해주세요

SELECT ID, NI.FISH_NAME, LENGTH
FROM FISH_INFO I JOIN FISH_NAME_INFO NI ON I.FISH_TYPE = NI.FISH_TYPE
WHERE LENGTH = (SELECT MAX(LENGTH)
                FROM FISH_INFO 
                GROUP BY FISH_TYPE 
                HAVING FISH_TYPE = I.FISH_TYPE);