-- 코드를 작성해주세요
WITH MAX_SCORE AS (
    SELECT G.EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_EMPLOYEES E JOIN HR_GRADE G
    ON E.EMP_NO = G.EMP_NO
    WHERE YEAR = 2022
    GROUP BY 1
    ORDER BY 2 DESC
    LIMIT 1
)

SELECT SCORE, E.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES E JOIN MAX_SCORE S
ON E.EMP_NO = S.EMP_NO
