-- 코드를 입력하세요
WITH MOST_VIEWS_BOARD AS (
    SELECT DISTINCT BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
)

SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE F JOIN MOST_VIEWS_BOARD M
ON F.BOARD_ID = M.BOARD_ID
ORDER BY FILE_ID DESC