-- 코드를 입력하세요
WITH MAX_TABLE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT F.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT F JOIN MAX_TABLE M
ON F.CATEGORY = M.CATEGORY
WHERE M.MAX_PRICE = F.PRICE
ORDER BY 2 DESC;